### ISSUE TITLE
Error calling indy_issue_credential_v2() issuing from askar wallet to askar-noncreds wallet

### ISSUE THREAD

**Issue by ianco** [Indicio-tech/acapy-minimal-example#177]
When I setup an `askar` issuer and an `askar-anoncreds` holder and then call `indy_issue_credential_v2()` I get the following exception.

Note that the credential is actually issued and received successfully - when I manually inspect the wallets afterwards the holder has the credential and the cred_exch record in both wallets is `state="done"`

```
controller        | Traceback (most recent call last):
controller        |   File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
controller        |     return _run_code(code, main_globals, None,
controller        |   File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
controller        |     exec(code, run_globals)
controller        |   File "/usr/src/app/example.py", line 324, in <module>
controller        |     asyncio.run(main())
controller        |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
controller        |     return loop.run_until_complete(main)
controller        |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
controller        |     return future.result()
controller        |   File "/usr/src/app/example.py", line 203, in main
controller        |     (alice_conn, bob_conn) = await connect_agents_and_issue_credentials(
controller        |   File "/usr/src/app/example.py", line 60, in connect_agents_and_issue_credentials
controller        |     inviter_cred_ex, _ = await indy_issue_credential_v2(
controller        |   File "/usr/src/app/.venv/lib/python3.10/site-packages/acapy_controller/protocols.py", line 648, in indy_issue_credential_v2
controller        |     holder_indy_record = await holder.event_with_values(
controller        |   File "/usr/src/app/.venv/lib/python3.10/site-packages/acapy_controller/controller.py", line 694, in event_with_values
controller        |     raise ControllerError(
controller        | acapy_controller.controller.ControllerError: Record from bob-anoncreds with topic issue_credential_v2_0_indy and values
controller        | 	{}
controller        | not received before timeout
```

The relevant line of code in the in the protocols class is:

```
    holder_indy_record = await holder.event_with_values(
        topic="issue_credential_v2_0_indy",
        event_type=V20CredExRecordIndy,
    )
```

... so maybe the event type is different?

**Comment by ianco** [comment]
Did a quick test with the alice/faber demo with the same configuration (askar issuer/anoncreds holder) and it looks like the event the holder receives is `issue_credential_v2_0_anoncreds`

Switched to the protocol methods implemented by @jamshale in the aca-py sceario tests (which test for askar vs anoncreds wallet type) and that seems to work.
