### ISSUE TITLE
Error on docker-compose run example

### ISSUE THREAD

**Issue by dbluhm** [Indicio-tech/acapy-minimal-example#22]
```
$ docker-compose run example
Traceback (most recent call last):
File "urllib3/connectionpool.py", line 670, in urlopen
File "urllib3/connectionpool.py", line 392, in _make_request
File "http/client.py", line 1255, in request
File "http/client.py", line 1301, in _send_request
File "http/client.py", line 1250, in endheaders
File "http/client.py", line 1010, in _send_output
File "http/client.py", line 950, in send
File "docker/transport/unixconn.py", line 43, in connect
FileNotFoundError: [Errno 2] No such file or directory 
```

**Comment by dbluhm** [comment]
Couldn't reproduce.
